config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users

  get 'sessions/new'
  get 'pois/new_distance', to: 'pois#new_distance'
  post 'pois/new_distance', to: 'pois#calculate_distance'
  get 'pois/result_distance', to: 'pois#result_distance'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  resources :pois
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poi.rb
class Poi < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  validates :x, presence: true, numericality: { greater_than: 0 }
  validates :y, presence: true, numericality: { greater_than: 0 }

  def euclidean_distance(p1, p2)
    sum_of_squares = 0
    p1.each_with_index do |p1_coord, index|
         sum_of_squares += (p1_coord - p2[index])**2
       end
    Math.sqrt(sum_of_squares).round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    def authorize
        redirect_to root_url unless logged_in?
    end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  before_action :authorize, except: [:new, :create]


  def index
    @pois = Poi.all
  end

  def show
    @poi = Poi.find(params[:id])
  end

  def new
    @poi = Poi.new
  end

  def create
    @poi = Poi.new(poi_params)
    if @poi.save
      redirect_to @poi
    else
      render 'new'
    end
  end

  def destroy
    @poi = Poi.find(params[:id])
    @poi.destroy

    redirect_to pois_path
  end

  def new_distance 
  end

  def calculate_distance
    @coordinate_x = params[:x].to_i
    @coordinate_y = params[:y].to_i
    @radius = params[:radius].to_i
    @pois = Poi.all
    @result_pois = [] 
    
    @pois.each do |poi|
      @result = Poi.new.euclidean_distance([@coordinate_x,@coordinate_y], [poi.x,poi.y])
      if @result <= @radius
        @result_pois.push(poi.name)
      end
    end
    render :result_distance
  end

  def result_distance
  end

private

  def poi_params
    params.require(:poi).permit(:name, :x, :y)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create  
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Usuário foi criado com sucesso!"
    #tire o método de comentário quando criar o helper.
    #Usuário depois de cadastrar-se acessa o sistema automaticamente
      sign_in
    else 
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render action: :edit
    end
  end

  def destroy
    @user = User.find(params[:id]) 
    @user.destroy
    sign_out
    redirect_to root_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    session[:user_id] = @user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def block_access
    redirect_to users_path if current_user.present?
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li>
            <ul>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>

app/views/pois/index.html.erb
<h1>Listing POI's</h1>
 
<table>
  <tr>
    <th>Name: </th>
    <th>Coordinate X: </th>
    <th>Coordinate Y: </th>
    <th></th>
  </tr>
 
  <% @pois.each do |poi| %>
    <tr>
      <td><%= poi.name %></td>
      <td><%= poi.x %></td>
      <td><%= poi.y %></td>
      <td><%= link_to 'Show', poi_path(poi) %></td>
      <td><%= link_to 'Destroy', poi_path(poi), method: :delete, data: { confirm: 'Are you sure about this?'} %></td>
    </tr>
  <% end %>

</table>

<%= link_to 'New Poi', new_poi_path %>
<%= link_to 'Calculate Distance', controller: "pois", action: "new_distance" %>

app/views/pois/new.html.erb
<h1>New POI</h1>


<%= form_with scope: :poi, url: pois_path, local: true do |form| %>

 <% if @poi.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@poi.errors.count, "error") %> prohibited
        this point_of_interest from being saved:
      </h2>
      <ul>
        <% @poi.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :x %><br>
    <%= form.number_field :x %>
  </p>

    <p>
    <%= form.label :y %><br>
    <%= form.number_field :y %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back To List', pois_path %>

app/views/pois/new_distance.html.erb
<h1>New Distance</h1>

<%= form_tag("/pois/new_distance", method: "post") do %>
  <%= label_tag :radius %><br>
  <%= number_field_tag :radius %>
  <br>
  <br>
  <%= label_tag :coordinate_x %><br>
  <%= number_field_tag :x %>
  <br>
  <br>
    <%= label_tag :coordinate_y %><br>
  <%= number_field_tag :y %>
  <p>
    <%= submit_tag("Submit") %>
  </p>
<% end %>


<%= link_to 'Back to List', pois_path %>

app/views/pois/result_distance.html.erb
<h1>Nearby Pois: </h1>
<% if @result_pois %>
  <% @result_pois.each do |poi| %>
    <p>
      Poi name: <%= poi %><br>
    </p>
  <% end %>
<% end %>

<%= link_to 'Back To List', pois_path %>

app/views/pois/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @poi.name %>
</p>
 
<p>
  <strong>Coordinate X:</strong>
  <%= @poi.x %>
</p>

<p>
  <strong>Coordinate Y:</strong>
  <%= @poi.y %>
</p>

<%= link_to 'Back to List', pois_path %>

app/views/users/index.html.erb
<h1> Users </h1>
 <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "Show", user %></td>
        </tr>
     <%end%>
   </tbody>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>

app/views/users/show.html.erb
<html>
    <body>
        <h3>Perfil de <%= @user.name %> </h3>
        <li><%= @user.email %></li>
        <%= link_to 'Pois List', pois_path %>
    </body>
</html>